version: '3'

services:
    web:
        build: .
        ports: 
            - "8000:80"
        depends_on:
            - db
        environment:
            - DB_CONNECTION_STRING=Server=db;Database=ShortUrlDb;User=sa;Password=Yukon900
    db:
        image: "microsoft/mssql-server-linux"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Yukon900"
            ACCEPT_EULA: "Y"